apiVersion: 1

contactPoints:
  - orgId: 1
    name: webhook-supervision
    receivers:
      - uid: webhook-receiver
        type: webhook
        settings:
          url: http://grafana-webhook:5001/
          httpMethod: POST

